.TH "prelude" 7
.SH NAME
Prelude \- Hybrid IDS framework

.SH DESCRIPTION
Prelude is a Hybrid IDS framework, that is, it is a product that enables all available security applications, be they open source or proprietary, to report to a centralized system. In order to achieve this task, Prelude relies on the IDMEF (Intrusion Detection Message Exchange Format) IETF standard, that enables different kinds of sensors to generate events using a unique language.

.B Prelude components:
.TP
.B The Prelude library:
Framework. 

Libprelude is the library that provides the framework used to access the Prelude system. It handles secure communications with one or several prelude-manager collectors, and provides an API (Application Programming Interface) to create IDMEF (Intrusion Detection Message Exchange Format) based events. 

It also provides important features like failover (saving to a local file for later retransmission, usage of a fallback route), in case one of the prelude-manager servers goes down. 

Moreover, it gives you the ability to create sensors that read events received by one or a set of prelude-managers. You could for example write an interactive notification system using this feature. 
.TP

.B Prelude-Manager:
Collects and normalize events.

The PreludeManager is a high-availability server which collects and normalizes information from distributed sensors and stores them into a database (or any kind of user-provided media). It also provides the ability to relay received events to one or several other prelude-manager servers. It also provides you the ability to filter received events so that you can provide specific actions for specific events. 


.B Prelude-LML:
Log analyzer, Syslog events collector. 

PreludeLML is a signature-based log analyzer monitoring your logfile and received syslog messages for suspicious activity. It handle events generated by a large set of components, including but not limited to: APC Emu, BigIP, Cisco PIX, Clamav, Dell-OM, Grsecurity, Honeyd, ipchains, Netfilter, ipfw, Nokia ipso, Apache ModSecurity?, Ms-SQL, Nagios, Norton Antivirus Corporate Edition, NTsyslog, Pam, Portsentry, Postfix, Proftpd, ssh, etc. 

Prelude-LML was written in order to easily integrate third party products, most particularly products that can't be modified directly to use the Prelude library. 
.TP

.B The PreludeDB library:
Easy access to the Prelude database. 

The PreludeDB Library provides an abstraction layer based upon the type and the format of the database used to store IDMEF alerts. 

It allows developers to use the Prelude IDMEF database easily and efficiently without worrying about SQL, and to access the database independently of the type/format of the database. 
.TP

.B Prewikka:
The Prelude-IDS console. 

Prewikka is a professional application providing advanced features like contextual filtering, aggregation, etc. Prewikka is a large step forward compared to Piwi.
.TP

.SH "SEE ALSO"
prelude-manager(1), prelude-adduser(1), prelude-lml(1), preludedb-admin(1), prewikka(1)

https://trac.prelude-ids.org/wiki/Introduction

.SH BUGS
This man page hadn't been proof-read yet.
